name: Update Profile Data

on:
  schedule:
    # Runs every 7hour
    - cron: '0 */10 * * *'
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  update-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Grant write permissions to the GITHUB_TOKEN

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use the latest Python 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run data update script
        run: python update_profile_data.py
